In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from scipy.stats import randint
import DiscreteCondEnt as DC

# 6 Discrete RV in (0, 1) where [0, 1, 5] depend on each others

In [11]:
low, high, RVsize, numRV = 0, 2, 1000, 6
depend = np.array([0, 1])
rv = DC.getRandomVar_select(randint.rvs, low, high, RVsize, numRV, depend)

[[1 1 0 ... 0 1 0]
 [1 0 1 ... 1 1 1]
 [1 1 1 ... 1 1 0]
 [0 0 1 ... 0 1 1]
 [1 1 1 ... 0 0 1]
 [0 1 1 ... 1 0 1]]


In [16]:
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier()

In [17]:
CVFold = 3
DC.computeEnt(rv, clf, DC.CondDEntropyScorer, DC.DiscreteEntropy, CVFold, True)

6  Discrete RVs with range [ 0 ,  2 ]
Resp	Cond	H(Resp|Cond)
0 	 [1] 	 1.0955097492006163
0 	 [2] 	 1.0974691854890641
0 	 [3] 	 1.0924310145600729
0 	 [4] 	 1.097942615544859
0 	 [5] 	 1.0963443506448132
0 	 [2 1] 	 1.096191627297684
0 	 [3 1] 	 1.091970200351952
0 	 [3 2] 	 1.0925686638274372
0 	 [4 1] 	 1.0908875956514537
0 	 [4 2] 	 1.0960066309732
0 	 [4 3] 	 1.0933755602698951
0 	 [5 1] 	 0.0
0 	 [5 2] 	 1.0931270643912467
0 	 [5 3] 	 1.0937699641313368
0 	 [5 4] 	 1.0928842987980243
0 	 [3 2 1] 	 1.0933418935648382
0 	 [4 2 1] 	 1.089127631781739
0 	 [4 3 1] 	 1.08956903513318
0 	 [4 3 2] 	 1.094356324736375
0 	 [5 2 1] 	 0.0
0 	 [5 3 1] 	 0.0
0 	 [5 3 2] 	 1.0910754411018073
0 	 [5 4 1] 	 0.0
0 	 [5 4 2] 	 1.0914516443436948
0 	 [5 4 3] 	 1.0945048892199158
0 	 [4 3 2 1] 	 1.0921545025004757
0 	 [5 3 2 1] 	 0.0
0 	 [5 4 2 1] 	 0.013898005776286896
0 	 [5 4 3 1] 	 0.020657457694893615
0 	 [5 4 3 2] 	 1.0944145764206725
0 	 [5 4 3 2 1] 	 0.252467408460416
1 	 [0] 	 1.091047029839

array([[1.09841535, 1.09550975, 1.09746919, 1.09243101, 1.09794262,
        1.09634435, 1.09619163, 1.0919702 , 1.09256866, 1.0908876 ,
        1.09600663, 1.09337556, 0.        , 1.09312706, 1.09376996,
        1.0928843 , 1.09334189, 1.08912763, 1.08956904, 1.09435632,
        0.        , 0.        , 1.09107544, 0.        , 1.09145164,
        1.09450489, 1.0921545 , 0.        , 0.01389801, 0.02065746,
        1.09441458, 0.25246741],
       [1.09735112, 1.09104703, 1.09474757, 1.09578035, 1.09540402,
        1.09462421, 1.09170725, 1.09417661, 1.0909142 , 1.09070993,
        1.0899899 , 1.09153045, 0.        , 1.09596869, 1.09362397,
        1.09240111, 1.087898  , 1.08801762, 1.09329444, 1.09243935,
        0.        , 0.        , 1.09145362, 0.        , 1.0920445 ,
        1.09085798, 1.0907562 , 0.        , 0.        , 0.02063205,
        1.09470122, 0.24532062],
       [1.09752662, 1.09387524, 1.09481545, 1.09432071, 1.09446423,
        1.09107626, 1.09313182, 1.09441412, 1.0905

# 6 Discrete RV in (0, 1, 2) where [0, 1, 5] depend on each others

In [24]:
low, high, RVsize, numRV = 0, 3, 1000, 6
depend = np.array([0, 1])
rv_D2 = DC.getRandomVar_select(randint.rvs, low, high, RVsize, numRV, depend)

[[2 2 2 ... 0 0 1]
 [1 2 1 ... 0 1 1]
 [2 1 0 ... 1 2 2]
 [0 0 1 ... 0 2 2]
 [1 0 1 ... 1 1 0]
 [0 1 0 ... 0 1 2]]


In [25]:
CVFold = 3
DC.computeEnt(rv_D2, clf, DC.CondDEntropyScorer, DC.DiscreteEntropy, CVFold, True)

6  Discrete RVs with range [ 0 ,  2 ]
Resp	Cond	H(Resp|Cond)
0 	 [1] 	 1.0967593801424604
0 	 [2] 	 1.0955928446636782
0 	 [3] 	 1.096118212096523
0 	 [4] 	 1.090249495013611
0 	 [5] 	 1.0966344421508232
0 	 [2 1] 	 1.0950422774674393
0 	 [3 1] 	 1.0953868929123847
0 	 [3 2] 	 1.0944687777882331
0 	 [4 1] 	 1.0886047278482893
0 	 [4 2] 	 1.0921411921190576
0 	 [4 3] 	 1.091117778806351
0 	 [5 1] 	 0.0
0 	 [5 2] 	 1.0925533838638024
0 	 [5 3] 	 1.093791056381879
0 	 [5 4] 	 1.0913549546282866
0 	 [3 2 1] 	 1.0943863871368664
0 	 [4 2 1] 	 1.0912848888900728
0 	 [4 3 1] 	 1.0896034196668913
0 	 [4 3 2] 	 1.0961206924301734
0 	 [5 2 1] 	 0.0
0 	 [5 3 1] 	 0.0
0 	 [5 3 2] 	 1.093714701266251
0 	 [5 4 1] 	 0.0
0 	 [5 4 2] 	 1.0939501139027652
0 	 [5 4 3] 	 1.0944851811065541
0 	 [4 3 2 1] 	 1.0913508962242249
0 	 [5 3 2 1] 	 0.0
0 	 [5 4 2 1] 	 0.020675963187303692
0 	 [5 4 3 1] 	 0.017148821174458224
0 	 [5 4 3 2] 	 1.0945905303594718
0 	 [5 4 3 2 1] 	 0.30158488965737046
1 	 [0] 	 1.09641

array([[1.09803217, 1.09675938, 1.09559284, 1.09611821, 1.0902495 ,
        1.09663444, 1.09504228, 1.09538689, 1.09446878, 1.08860473,
        1.09214119, 1.09111778, 0.        , 1.09255338, 1.09379106,
        1.09135495, 1.09438639, 1.09128489, 1.08960342, 1.09612069,
        0.        , 0.        , 1.0937147 , 0.        , 1.09395011,
        1.09448518, 1.0913509 , 0.        , 0.02067596, 0.01714882,
        1.09459053, 0.30158489],
       [1.09757633, 1.09641115, 1.09240341, 1.09507284, 1.09438776,
        1.09523809, 1.09214627, 1.09294843, 1.09326237, 1.09084065,
        1.09335019, 1.09475032, 0.        , 1.09297944, 1.09447179,
        1.09271017, 1.09374661, 1.09090058, 1.08966288, 1.09467968,
        0.        , 0.        , 1.09378294, 0.        , 1.09247484,
        1.09209789, 1.08981547, 0.0237079 , 0.02093163, 0.02387442,
        1.09492973, 0.25924894],
       [1.09808264, 1.09675689, 1.09763727, 1.09564684, 1.09335901,
        1.09550928, 1.09555272, 1.09485304, 1.0954

In [28]:
 DC.computeEnt(rv_D2, clf, DC.NegLogLikeScorer, DC.DiscreteEntropy, CVFold, True)

6  Discrete RVs with range [ 0 ,  2 ]
Resp	Cond	H(Resp|Cond)
0 	 [1] 	 0.0033540837355938986
0 	 [2] 	 0.0033930182804875228
0 	 [3] 	 0.003280508023834276
0 	 [4] 	 0.0033978609697213765
0 	 [5] 	 0.0030449949333635484
0 	 [2 1] 	 0.0032886479185105805
0 	 [3 1] 	 0.003199738474511394
0 	 [3 2] 	 0.003075965486469642
0 	 [4 1] 	 0.0032684624472720334
0 	 [4 2] 	 0.0031536057203459776
0 	 [4 3] 	 0.003308409879975115
0 	 [5 1] 	 0.0
0 	 [5 2] 	 0.0032348637715205
0 	 [5 3] 	 0.003003434177997094
0 	 [5 4] 	 0.003376049230185373
0 	 [3 2 1] 	 0.0033023172019732267
0 	 [4 2 1] 	 0.0032174985447943304
0 	 [4 3 1] 	 0.0031623974148677846
0 	 [4 3 2] 	 0.0032729547836655506
0 	 [5 2 1] 	 0.0
0 	 [5 3 1] 	 0.0
0 	 [5 3 2] 	 0.0031416662399599946
0 	 [5 4 1] 	 0.0
0 	 [5 4 2] 	 0.0032051697316795203
0 	 [5 4 3] 	 0.0033390387771453263
0 	 [4 3 2 1] 	 0.003082520793598191
0 	 [5 3 2 1] 	 2.9977770845314742e-05
0 	 [5 4 2 1] 	 4.734342846074429e-05
0 	 [5 4 3 1] 	 3.823733303846865e-05
0 	 [5 4

array([[1.09803217e+00, 3.35408374e-03, 3.39301828e-03, 3.28050802e-03,
        3.39786097e-03, 3.04499493e-03, 3.28864792e-03, 3.19973847e-03,
        3.07596549e-03, 3.26846245e-03, 3.15360572e-03, 3.30840988e-03,
        0.00000000e+00, 3.23486377e-03, 3.00343418e-03, 3.37604923e-03,
        3.30231720e-03, 3.21749854e-03, 3.16239741e-03, 3.27295478e-03,
        0.00000000e+00, 0.00000000e+00, 3.14166624e-03, 0.00000000e+00,
        3.20516973e-03, 3.33903878e-03, 3.08252079e-03, 2.99777708e-05,
        4.73434285e-05, 3.82373330e-05, 3.21635939e-03, 7.05189699e-04],
       [1.09757633e+00, 3.15027101e-03, 3.20303386e-03, 3.41306842e-03,
        3.15203864e-03, 3.02404188e-03, 3.09191400e-03, 3.17104338e-03,
        3.15167350e-03, 3.37845467e-03, 3.12065518e-03, 3.12556678e-03,
        0.00000000e+00, 3.28705645e-03, 3.16237582e-03, 3.30751675e-03,
        3.40283729e-03, 3.22655543e-03, 3.30549369e-03, 3.24999765e-03,
        0.00000000e+00, 0.00000000e+00, 3.10158821e-03, 0.00000

# 3 Uniform RV in (0,1)

In [29]:
low, high, RVsize, numRV = 0, 1, 1000, 6
depend = np.array([0, 1])
rv_c = DC.getRandomVar_select(np.random.uniform, low, high, RVsize, numRV, depend)

[[0.62288178 0.89864673 0.42757121 ... 0.55246038 0.35055875 0.19814201]
 [0.80467222 0.40553277 0.35035364 ... 0.80105127 0.59840883 0.85096125]
 [0.96271045 0.20782952 0.35927898 ... 0.93760044 0.56953262 0.7175228 ]
 [0.34100553 0.25518242 0.87094284 ... 0.88994968 0.49870284 0.93697323]
 [0.49672003 0.19250257 0.99925421 ... 0.19995449 0.19663666 0.96349845]
 [0.427554   0.3041795  0.77792485 ... 0.35351165 0.94896757 0.04910326]]


In [4]:
from sklearn.metrics import mean_squared_error
def logMSEscorer(clf, X, y):
    y_est = clf.predict(X)
    return mean_squared_error(y, y_est)

In [5]:
def varEntropy(y):
    return np.var(y)

In [30]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(n_neighbors=numRV)

CVFold = 3
Entropy = DC.computeEnt(rv_c, regressor,logMSEscorer, varEntropy, CVFold, True)

6  Discrete RVs with range [ 0.00016440023697739115 ,  0.9997999051425056 ]
Resp	Cond	H(Resp|Cond)
0 	 [1] 	 0.0963759207558909
0 	 [2] 	 0.09207467120347501
0 	 [3] 	 0.09149076023372489
0 	 [4] 	 0.0925625084989234
0 	 [5] 	 0.09406651560767913
0 	 [2 1] 	 0.09148681416542338
0 	 [3 1] 	 0.0960933155440931
0 	 [3 2] 	 0.09323843216920231
0 	 [4 1] 	 0.09624459803703479
0 	 [4 2] 	 0.09394516665693066
0 	 [4 3] 	 0.09739906596280168
0 	 [5 1] 	 0.013303348562462916
0 	 [5 2] 	 0.09355923260719996
0 	 [5 3] 	 0.09941387829769888
0 	 [5 4] 	 0.09762898891475143
0 	 [3 2 1] 	 0.09730607438336945
0 	 [4 2 1] 	 0.09633355845625267
0 	 [4 3 1] 	 0.09354609264738299
0 	 [4 3 2] 	 0.09395064743468406
0 	 [5 2 1] 	 0.02545399297938587
0 	 [5 3 1] 	 0.027363487710695855
0 	 [5 3 2] 	 0.09311466102219285
0 	 [5 4 1] 	 0.024830394546410298
0 	 [5 4 2] 	 0.09499556473817032
0 	 [5 4 3] 	 0.09573463124747798
0 	 [4 3 2 1] 	 0.09553147022609854
0 	 [5 3 2 1] 	 0.04258045913062942
0 	 [5 4 2 1] 	 0.0