In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from scipy.stats import randint
import DiscreteCondEnt as DC

from sklearn.metrics import mean_squared_error
def MSEscorer(clf, X, y):
    y_est = clf.predict(X)
    return np.log(mean_squared_error(y, y_est)*np.pi*2)/2

def varEntropy(y):
    return np.log(np.var(y)*np.pi*2)/2

from sklearn.linear_model import LinearRegression
linReg = LinearRegression()

from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor()

# x = np.random.multivariate_normal( mean=[0,0],
#                                   cov=[[1,1],[1,1]],
#                                  size = 300)
# x = np.transpose(x)

low, high, RVsize, numRV = 0, 2, 1000, 6
depend = np.array([0, 1])
rv = DC.getRandomVar_select(randint.rvs, low, high, RVsize, numRV, depend)

CVFold = 3
DEntropy = DC.computeEnt(rv, linReg, MSEscorer, varEntropy, CVFold)

[[1 0 0 ... 1 1 1]
 [1 0 0 ... 1 0 0]
 [1 1 1 ... 0 1 1]
 [1 1 1 ... 1 1 0]
 [1 0 1 ... 1 1 1]
 [0 0 0 ... 0 1 1]]


In [2]:
# print( DEntropy[:,1:], DEntropy[:,0])
MI = np.broadcast_to(DEntropy[:,0][:,None], DEntropy[:,1:].shape) - DEntropy[:,1:]

In [24]:
# MI
#assume sset is a one-dimensional array
# sprev[]
# for i in sset.size:
#     resp = sset[i]
#     snext[]
#     if i >= 
#     for j in range(i+1, sset.size):
#         snext.append(sset[j])
#     #compute
#     sprev.append(sset[i])
#123=E[{1|23},{2|13},{3|12}]
index = np.ma.array(np.arange(numRV), mask=False)
j = 0
def MMI(index, j, MI):
    setSize = index.size - np.ma.count_masked(index)
    MI_set = 0
    k = 0
    j_set = 0
    if (setSize > 1):
        if (j == j_set):
            print ("MI[{0}] = 1/{1}*E(".format(index, setSize -1))
        for i in range(index.size):
            if (index.mask[i] == False):
                index.mask[i] = True
                ci = DC.ConditionIndex(numRV, i, index) - 1
                MI_set += MI[i,int(ci)]
                if (j == j_set):
                    print("MI[{0},{1}] ".format(i,index), end = '')
                if (np.ma.count_masked(index) < index.size):
                    j_next = j + 1
                    subMI = MMI(index, j_next, MI)
                    MI_set += subMI*(setSize - 2)
                    if (j == j_set):
                        print("+ {0}*MI[{1}]".format(setSize-2, index), end='')
                index.mask[i] = False
                k += 1
                if (k < setSize):
                    if (j == j_set):
                        print(" , ")
                else:
                    if (j == j_set):
                        print("")
                    break
        MI_set /= (setSize - 1)
        MI_set /= setSize
        if (j == j_set):
            print (") = {0}".format(MI_set))
    return MI_set
MMI(index, j, MI)

MI[[0 1 2 3 4 5]] = 1/5*E(
MI[0,[-- 1 2 3 4 5]] + 4*MI[[-- 1 2 3 4 5]] , 
MI[1,[0 -- 2 3 4 5]] + 4*MI[[0 -- 2 3 4 5]] , 
MI[2,[0 1 -- 3 4 5]] + 4*MI[[0 1 -- 3 4 5]] , 
MI[3,[0 1 2 -- 4 5]] + 4*MI[[0 1 2 -- 4 5]] , 
MI[4,[0 1 2 3 -- 5]] + 4*MI[[0 1 2 3 -- 5]] , 
MI[5,[0 1 2 3 4 --]] + 4*MI[[0 1 2 3 4 --]]
) = -0.0030892566145769244


-0.0030892566145769244